-- タグ情報を保持するテーブル
CREATE TABLE tags (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(50 CHAR) UNIQUE NOT NULL
);

-- 投稿とタグの多対多関係を結ぶ中間テーブル
CREATE TABLE post_tags (
    post_id NUMBER NOT NULL,
    tag_id NUMBER NOT NULL,
    PRIMARY KEY (post_id, tag_id),
    CONSTRAINT fk_post_tags_post FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE CASCADE,
    CONSTRAINT fk_post_tags_tag FOREIGN KEY (tag_id) REFERENCES tags(id) ON DELETE CASCADE
);
